parameters:
#    social_network_event.example.class: SocialNetwork\Bundle\EventBundle\Example

services:
#    social_network_event.example:
#        class: %social_network_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
