parameters:
#    social_network_login.example.class: SocialNetwork\Bundle\LoginBundle\Example

services:
#    social_network_login.example:
#        class: %social_network_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
