parameters:
#    social_network_friend.example.class: SocialNetwork\Bundle\FriendBundle\Example

services:
#    social_network_friend.example:
#        class: %social_network_friend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
