parameters:
#    social_network_profile.example.class: SocialNetwork\Bundle\ProfileBundle\Example

services:
#    social_network_profile.example:
#        class: %social_network_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
