parameters:
#    social_network_follow.example.class: SocialNetwork\Bundle\FollowBundle\Example

services:
#    social_network_follow.example:
#        class: %social_network_follow.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
